#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	5
bspc config window_gap		20

bspc config normal_border_color		"#101933"
bspc config focused_border_color	"#18264d"

bspc config focus_follows_pointer	true
bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

xsetroot -solid "#050810" &
xsetroot -cursor_name left_ptr &
