#!/bin/sh

#inspired by gk
_c() { bspc config "$@"; }
_m() { bspc monitor "$@"; }
_s() {
	pkill -x "$1"
	{
		sleep 0.1
		"$@" &
	}
}

#monitors
_m -d I II III IV V

#borders
_c border_width 10
_c normal_border_color "#261c1f"
_c focused_border_color "#3d292e"
_c borderless_monocle false
_c gapless_monocle false

#misc
_c window_gap 20
_c focus_follows_pointer true

#startup
_s sxhkd
_s picom -b
_s xsetroot -cursor_name left_ptr
_s ~/.fehbg
_s xrdb -load ~/.Xresources
_s pulseaudio -D
