#!/bin/bash

cd /home/safin/Documents/aeacus/
cp /home/safin/Documents/vault/ca-crypto.go cmd/crypto.go

make release
unzip aeacus-win32.zip 1>/dev/null
unzip aeacus-linux.zip 1>/dev/null

7z a -y -bsp0 -bso0 -mx=9 -mfb=273 -ms=on aeacus-win32.7z aeacus-win32/ &>/dev/null
7z a -y -bsp0 -bso0 -mx=9 -mfb=273 -ms=on aeacus-linux.7z aeacus-linux/ &>/dev/null

rm -rf aeacus-win32/
rm -rf aeacus-linux/

rm -rf aeacus-win32.zip
rm -rf aeacus-linux.zip

git reset --hard HEAD
notify-send "Aeacus builds finished!"
