#!/bin/bash

c="$(tput setaf 6)$(tput bold)"
w="$(tput setaf 8)"
r="$(tput sgr0)"

wm=$(wmctrl -m |
   grep "Name" |
   cut -d " " -f2)
os=$(
   . /etc/os-release
   echo "$ID"
)
pk=$(pacman -Qq | wc -l)

echo "${w}  卑    ${c}os ${r}$os
${w} 卑卑   ${c}wm ${r}$wm
${w}卑卑卑  ${c}pk ${r}$pk
"
