#!/bin/bash

w="$(tput setaf 8)"
c="$w$(tput bold)"
r="$(tput sgr0)$(tput setaf 8)"

wm=$(wmctrl -m |
   grep "Name" |
   cut -d " " -f2)
os=$(
   . /etc/os-release
   echo "$ID"
)
pk=$(pacman -Qq | wc -l)

echo "${w}  卑    ${c}os :: ${r}$os
${w} 卑卑   ${c}wm :: ${r}$wm
${w}卑卑卑  ${c}pk :: ${r}$pk
"
