#!/bin/bash

export DOTS="/home/safin/.dots"

rm -rf $DOTS/.config/*
rm -rf $DOTS/.bin
rm -rf $DOTS/.zsh
rm -rf $DOTS/.Xresources
rm -rf $DOTS/.zshrc

cp -Rf ~/.config/termite 		$DOTS/.config
cp -Rf ~/.config/img			$DOTS/.config
cp -Rf ~/.config/nvim			$DOTS/.config
cp -Rf ~/.config/picom			$DOTS/.config
cp -Rf ~/.config/xob			$DOTS/.config
cp -Rf ~/.config/awesome		$DOTS/.config
cp -Rf ~/.config/dmenu			$DOTS/.config

cp -Rf ~/.zsh					$DOTS/.zsh
cp -Rf ~/.bin					$DOTS/.bin
cp -Rf ~/.Xresources			$DOTS/.Xresources
cp -Rf ~/.zshrc					$DOTS/.zshrc

rm -rf $DOTS/.bin/phicom

cd $DOTS && push "updots"
