alias mirror="xrandr --output DP-1 --auto --same-as eDP-1"
alias ls="exa --icons --group-directories-first"
alias la="exa -a --icons --group-directories-first"
alias ll="exa -l -a --icons --group-directories-first"
alias tree="exa -a --icons --tree --group-directories-first"
alias npm="pnpm"
alias bat="bat --theme base16"
alias xwin="Xephyr -br -ac -noreset -screen 1600x900 :2"
alias xdisp="DISPLAY=:2"
alias grep="grep --color=auto"
alias ip="ip -color=auto"
alias record="scr -m s -f 60 -c -n"
alias git="hub"
alias clock="tty-clock -C 1"
alias vim="nvim"
alias gpg="gpg2"
alias o="open"

precmd() $funcstack[1]() echo
