export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'
export JAVA_HOME='/usr/lib/jvm/java-8-openjdk'
export ANDROID_SDK_ROOT='/opt/android-sdk'
export SCR_DIR='/home/safin/Documents/scr/img'
export REC_DIR='/home/safin/Documents/scr/vid'
export PATH="/home/safin/Documents/vault:/home/safin/dots/scripts/minfetch:/home/safin/dots/scripts:/home/safin/go/bin:$PATH"
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'
export TERM="xterm-256color"
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=1000
