#!/bin/sh
clear

i=" "

r='\033[0;31m'
g='\033[0;32m'
y='\033[0;33m'
b='\033[0;34m'
c='\033[0;35m'
s='\033[0m'

#intro
printf "~ @iota ~\n"

#colors
printf "%s%s" "$r" "$i"
printf "%s%s" "$g" "$i"
printf "%s%s" "$y" "$i"
printf "%s%s" "$b" "$i"
printf "%s%s" "$c" "$i"

#cleanup
printf "%s\n\n" "$s"
