#!/bin/sh

dots="$HOME/dots/"

sy() {
	d=$(dirname "${dots}$1")
	mkdir -p "$d"
	cp -Rf "$1" "$d"
}

s() {
	d=$(dirname "${dots}home$1")
	mkdir -p "$d"
	cp -Rf "${HOME}$1" "$d"
}

ry() {
	rm -rf "${dots}$1"
}

r() {
	rm -rf "${dots}home$1"
}

r "/*"
ry "/*"

s "/.zshrc"
s "/.Xresources"
s "/.gitconfig"
s "/.bin"
s "/.config/bspwm"
s "/.config/sxhkd"
s "/.config/alacritty"
s "/.config/picom"
s "/.config/rofi"
s "/.config/nvim"
r "/.config/nvim/plugged"

sy "/etc/systemd/logind.conf"
sy "/etc/ly/config.ini"

cd "$HOME/dots" && p
