#!/bin/bash

[[ -n $1  ]]  &&  C="$1 "   || C=" "           # reset
[[ -n $SP ]]  &&  SP=$SP    || SP="    "        # spacing
[[ -n $BL ]]  &&  BL="$BL"  || BL='\033[0;30m'  # black
[[ -n $M  ]]  &&  M="$M"    || M='\033[0;35m'   # magenta
[[ -n $R  ]]  &&  R="$R"    || R='\033[0;31m'   # red
[[ -n $Y  ]]  &&  Y="$Y"    || Y='\033[0;33m'   # yellow
[[ -n $G  ]]  &&  G="$G"    || G='\033[0;32m'   # green
[[ -n $CY ]]  &&  CY="$CY"  || CY='\033[0;36m'  # cyan
[[ -n $BU ]]  &&  BU="$BU"  || BU='\033[0;34m'  # blue
[[ -n $W  ]]  &&  W="$W"    || W='\033[0;37m'   # white

printf "\n$SP"
for CL in $BL $M $R $Y;  do printf "$CL$C"; done

printf "\n$SP"
for CL in $G $CY $BU $W; do printf "$CL$C"; done

echo && echo
