#!/bin/bash

sep=" "
os="mj"
wm=$(wmctrl -m | grep "Name" | cut -d: -f2 | cut -d" " -f2)
up=$(uptime | awk '{ print $1 }' | awk ' BEGIN { FS=":" }; { print $1 } ')

clear
printf "$sep \033[0;31m\033[1mos  \033[0m$os
$sep \033[0;31m\033[1mwm  \033[0m$wm
$sep \033[0;31m\033[1mup  \033[0m$up

"
