#!/bin/bash

export DIR="/home/safin/dots/.config/polybar"
mode=$(cat $DIR/mode)

if $(echo "$mode" | grep -qw "d"); then
  sed -i 's/f0f0f0/050506/g' $DIR/config
  sed -i 's/050505/f0f0f1/g' $DIR/config
  echo "l" >$DIR/mode
fi

if $(echo "$mode" | grep -qw "l"); then
  sed -i 's/050506/f0f0f0/g' $DIR/config
  sed -i 's/f0f0f1/050505/g' $DIR/config
  echo "d" >$DIR/mode
fi
