#!/bin/bash

killall dunst

export DOTS="/home/safin/dots"
export POLY="$DOTS/.config/polybar/config"
export DUNST="$DOTS/.config/dunst/dunstrc"
export MODE_DIR="$DOTS/scripts/colormode/mode"
export MODE=$(cat $MODE_DIR)

export D_BG="050505"
export D_FG="f0f0f0"
export L_BG="f0f0f1"
export L_FG="050506"

switch() {
  if $(echo "$MODE" | grep -qw "d"); then
    sed -i "s/$D_FG/$L_FG/g" $1
    sed -i "s/$D_BG/$L_BG/g" $1
    echo "l" >$MODE_DIR
  fi
  if $(echo "$MODE" | grep -qw "l"); then
    sed -i "s/$L_FG/$D_FG/g" $1
    sed -i "s/$L_BG/$D_BG/g" $1
    echo "d" >$MODE_DIR
  fi
}

switch $POLY
switch $DUNST

dunst &
